static void quit(void);
static void clearMessage(void);
static void newLine(void);
static void goToLineStart(void);
static void goToLineEnd(void);
static void switchInsertMode(void);
static void switchInsertModeStart(void);
static void switchInsertModeAppend(void);
static void switchInsertModeAppendEnd(void);
